name: Build and Release CV

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - '.github/workflows/build_cv.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Compile main.tex by XeLaTeX
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      # move pdf to output
      - name: Move pdf to output folder
        run: |
          mkdir -p output
          cp main.pdf output/cv.pdf

      # Optionalï¼šupload artifact to Actions
      - name: Upload pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: output/cv.pdf

      # create Release and upload pdf
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # new tag
          tag_name: cv-${{ github.run_number }}
          name: "CV update ${{ github.run_number }}"
          files: output/cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
